server:
  port: 9000

spring:
  application:
    name: demo-aws-secrets
  config:
    import: aws-secretsmanager:/secret/demo-aws-secrets, aws-parameterstore:/config/demo-aws-secrets

management:
  endpoints:
    web:
      exposure:
        include: env, health

app-credentials:
  client-id: ${clientId}
  client-secret: ${clientSecret}

http:
  base-uri: ${.application.baseUri}
  api-gateway-id: ${.application.apiGatewayId}